### ISSUE TITLE
maven location for 3.0.0? (bintray sunset)

### ISSUE THREAD

**Issue by sublime392** [triniwiz/fancycamera#21]
Hi @triniwiz I am using the nativescript-camera-plus, but I keep running into problems because bintray keeps intermittently turning off their service in order to warn users that bintray is going away on May 1st. 

Is there another Maven location I should be using?
Thanks!

**Comment by triniwiz** [comment]
I already have [something](https://issues.sonatype.org/browse/OSSRH-67362) in the works but first the package name needs updating.

**Comment by serglokhm** [comment]
Hi @triniwiz
Could you please upload the package to the new Maven location?
Thanks a lot!
