### ISSUE TITLE
Error en camera plus nativescript @nstudio

### ISSUE THREAD

**Issue by DevZatokio** [triniwiz/fancycamera#24]
Camera Plus Nativescript version 3.3.0  
Could not GET 'https://dl.bintray.com/triniwiz/maven/com/github/triniwiz/fancycamera/3.0.0-alpha19/fancycamera-3.0.0-alpha19.pom'. Received status code 403 from server: Forbidden

**Comment by triniwiz** [comment]
You need `3.4.0`

**Comment by DevZatokio** [comment]
occupying 3.4.0 I get these errors
`
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.0.0
-rc04]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: androidx.camera:camera-view:1.0.0-alpha24 -> androidx.camera:camera-core@[1.0.0-rc04], but camera-co
re version was 1.0.0.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto io.github.triniwiz:fancycamera@3.0.0-alpha23
-- Project 'app' depends onto androidx.camera:camera-lifecycle@{strictly 1.0.0}
-- Project 'app' depends onto androidx.camera:camera-view@{strictly 1.0.0-alpha24}
-- Project 'app' depends onto androidx.camera:camera-camera2@{strictly 1.0.0}
-- Project 'app' depends onto androidx.camera:camera-core@{strictly 1.0.0}
-- Project 'app' depends onto io.github.triniwiz:fancycamera@{strictly 3.0.0-alpha23}`

**Comment by DevZatokio** [comment]
My solution was to change to 3.3.0 and change node_modules that called 19, I put the one you have productive, which is 18
